# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = FaceBase
DESTDIR = ../../bin/FaceBase
QT += core widgets gui
CONFIG += debug console
DEFINES += WIN64
INCLUDEPATH += ./../includes
DEPENDPATH += .
MOC_DIR += ./GeneratedFiles/debug
OBJECTS_DIR += debug
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
include(FaceBase.pri)
